### ISSUE TITLE
Rename Checklist and Briefing Form Documents

### ISSUE THREAD

**Issue by frostyandy2k** [TobiasGraef/Exp-SE#3]
Checklist -> ?
Briefing Form -> ?

Coole Namen wie PICOT oder FINER

Vorschläge:
Student Helper in Technology 
Computer Scientists Guide (CSG)

**Comment by frostyandy2k** [comment]
Reason for closing ?

**Comment by TobiasGraef** [comment]
We renamed the documents. If you think the names dont fit or should be improved, we can reopen it.

**Comment by frostyandy2k** [comment]
What was the rename?

Checklist -> ?
Briefing Form -> ?

**Comment by frostyandy2k** [comment]
Updated release with new name (SPID)
