### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by lorey** [TobiasGraef/Exp-SE#5]
Love the document, @frostyandy2k told me about it. To improve the visibility, I suggest to expand the readme file by focusing on the user benefit of the checklist. For example, a preview of the checklist would be great. Will try to open a pull request, if I find the time to.

Great work guys!

**Comment by scaleit** [comment]
We agree and will update it soon.

**Comment by frostyandy2k** [comment]
Updated at the new repo: https://github.com/teco-kit/Exp-SE

Check it out!
