### ISSUE TITLE
Fork repository to TECO and mention the permanent move

### ISSUE THREAD

**Issue by scaleit** [TobiasGraef/Exp-SE#6]

**Comment by TobiasGraef** [comment]
I could just transfer ownership of the repository, but i need to know the destination.

**Comment by frostyandy2k** [comment]
This is the new destination:
https://github.com/teco-kit/Exp-SE

**Comment by TobiasGraef** [comment]
I cant transfer it to the organization teco-kit, because i am not allowed to create repositories there (and a repository with the same name already exists). Therefor I would transfer it to you and move it to teco-kit.

**Comment by frostyandy2k** [comment]
It's already forked, just updated the readme with a link to the new destination.

Done
